config/routes.rb
Rails.application.routes.draw do

  get 'devices/index'
  get 'devices/show'
  get 'devices/edit'
  get 'devices/create'
  get 'devices/update'
  get 'devices/destroy'
  resources :listings

  root 'listings#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :listings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :find_listing, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      @listings = Listing.where(:user_id => current_user.id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @listing = Listing.new
  end

  def create

    @listing = Listing.new(listing_params)
    if @listing.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @listing.update(listing_params)
      redirect_to listing_path(@listing)
    else
      render 'edit'
    end
  end

  def destroy
    @listing.destroy
    redirect_to root_path
  end

  private

  def listing_params
    params.require(:listing).permit(:title)
  end

  def find_listing
    @listing = Listing.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/devices/create.html.erb
<h1>Devices#create</h1>
<p>Find me in app/views/devices/create.html.erb</p>

app/views/devices/destroy.html.erb
<h1>Devices#destroy</h1>
<p>Find me in app/views/devices/destroy.html.erb</p>

app/views/devices/edit.html.erb
<h1>Devices#edit</h1>
<p>Find me in app/views/devices/edit.html.erb</p>

app/views/devices/index.html.erb
<h1>Devices#index</h1>
<p>Find me in app/views/devices/index.html.erb</p>

app/views/devices/show.html.erb
<h1>Devices#show</h1>
<p>Find me in app/views/devices/show.html.erb</p>

app/views/devices/update.html.erb
<h1>Devices#update</h1>
<p>Find me in app/views/devices/update.html.erb</p>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-light" style="background-color: #d03a12">
  <div class="container">

    <a class="navbar-brand" href="#">
      <img src="http://rabbu.com/wp-content/uploads/2017/01/rabbu-light.png" alt="Rabbu" width="100px">
    </a>
    <ul class="nav">
      <% if !current_user.present? %>
        <li class="nav-link"><%= link_to 'Sign-Up', new_user_registration_path, style: "color: white" %></li>
      <% end %>
      <% if current_user.present? %>
        <li class="nav-link"><%= link_to 'My Listings', root_path, style: "color: white" %></li>
        <li class="nav-link"><%= link_to 'Sign-Out', destroy_user_session_path, method: :delete, style: "color: white" %></li>
      <% else %>
        <li class="nav-link"><%= link_to 'Log-In', new_user_session_path, style: "color: white" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_static_landing_page.html.erb
<div class="jumbotron">
  <h1 class="display-4">Welcome to Rabbu</h1>
  <p class="lead">Property Management & Automation Experts</p>
  <hr class="my-4">
  <h5>Let us handle the hard work to maximize your rental income</h5>
  <%= link_to "Let's Get Started", new_user_registration_path, style: "color: white; margin-top: 2rem", class: "btn btn-danger btn-lg" %>
  <%= link_to "Sign-In", new_user_session_path, style: "color: white; margin-top: 2rem", class: "btn btn-danger btn-lg" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RabbuCodingChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container master-container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/listings/_forms.html.erb
<%= simple_form_for @listing do |f| %>
  <h5><%= f.input :title, label: "Listings:" %></h5>

    <%= link_to "Back", root_path, class: "btn btn-sm btn-primary"%>
    <%= f.button :submit, class: "btn btn-sm btn-secondary" %>

<% end %>

app/views/listings/edit.html.erb
<h2>Edit Listing</h2>

<%= render 'forms' %>

app/views/listings/index.html.erb
<% if user_signed_in? %>
  <h1>Your Listings</h1>
  <p>Add a listing or click property to view details</p>
  <% @listings.each do |listing| %>
    <h4><%= link_to listing.title, listing, style: "color: #212121" %></h4>
  <% end %>
  <button type="button" class="btn btn-success" style="margin-top: 2rem"><%= link_to "Add Listing", new_listing_path, style: "color: white" %></button>
<% else %>
  <%= render 'layouts/static_landing_page' %>
<% end %>

app/views/listings/new.html.erb
<h2 style="margin-bottom: 2rem">Create a new listing</h2>

<%= render 'forms' %>

app/views/listings/show.html.erb
<h2><%= @listing.title %></h2>

<div style="margin-top: 2rem">
  <%= link_to "Add Device", edit_listing_path(@listing), class: "btn btn-sm btn-info" %>
  <%= link_to "Edit Device", edit_listing_path(@listing), class: "btn btn-sm btn-secondary" %>
  <%= link_to "Delete Device", edit_listing_path(@listing), class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "Are you sure you want to delete this device?"} %>

</div>
<hr>
<div style="margin-top: 3rem">
  <%= link_to "Back", root_path, class: "btn btn-sm btn-primary"%>
  <%= link_to "Edit Listing", edit_listing_path(@listing), class: "btn btn-sm btn-secondary" %>
  <%= link_to "Delete Listing", listing_path(@listing), class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "Are you sure you want to delete this listing?"} %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>